language: node_js
node_js:
  - 12.13.0
services: postgresql
cache:
  directories:
    - $HOME/.npm
before_script:
  - cd ./backend
  - yarn install --prod false
  - psql -c 'CREATE DATABASE finanzie_test;' -U postgres
  - yarn db:migrate-test
script:
  - yarn lint
  - yarn test --coverage
  - yarn audit
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script: bash -c 'ssh-keyscan -H $SERVER_IP >> $HOME/.ssh/known_hosts && sh ./release.sh'
  on:
    branch: master
