jobs:
  include:
    - stage: SQA pipeline
      services: docker
      install:
        - docker build -f ./backend/Dockerfile.dev -t balans-backend ./backend
        - docker build -f ./web/Dockerfile.dev -t balans-web ./web
        - docker pull postgres:12-alpine
      before_script:
        - docker run -d --network host -e POSTGRES_PASSWORD=balans -e POSTGRES_DB=balans_test postgres:12-alpine
      script:
        - docker run balans-backend yarn lint
        - docker run -e CI -e SECRET=travis -e DB_USERNAME=postgres -e DB_PASSWORD=balans --network host balans-backend sh -c "yarn db:test:migrate && yarn test --coverage"
        - docker run balans-backend yarn audit
        - docker run balans-web yarn lint
    - stage: Release pipeline
      if: type = push AND branch = release
      language: node_js
      node_js: 12.13.0
      services: docker
      cache: yarn
      install:
        - docker build -t nacho19/balans-backend ./backend
        - docker build -t nacho19/balans-web ./web
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker run -v $(pwd)/web/build:/app/build nacho19/balans-web
      after_success:
        - docker push nacho19/balans-backend
        - zip -r release.zip Dockerrun.aws.json
      deploy:
        - provider: s3
          access_key_id: $IAM_ID
          secret_access_key: $IAM_SECRET
          skip_cleanup: true
          bucket: balans.cf
          acl: public_read
          local_dir: web/build
          region: sa-east-1
          on:
            branch: release
        - provider: elasticbeanstalk
          skip_cleanup: true
          access_key_id: $IAM_ID
          secret_access_key: $IAM_SECRET
          region: sa-east-1
          app: balans-server
          env: default-env
          bucket: elasticbeanstalk-sa-east-1-511811702480
          zip_file: ./release.zip
          on:
            branch: release
        - provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
          on:
            branch: release
branches:
  only:
    - dev
    - release
