language: node_js
node_js:
  - 12.13.0
services: postgresql
cache: yarn
jobs:
  include:
    - stage: Pipeline
      env:
        - PORT=5000
        - SECRET=test
        - API_URL=http://localhost:5000/graphql
      install:
        - psql -c 'CREATE DATABASE finanzie_test;' -U postgres
        - yarn --cwd backend install --frozen-lockfile
        - yarn --cwd web install --frozen-lockfile
        - yarn --cwd web cypress install
        - yarn --cwd backend db:test:migrate
      script:
        - yarn --cwd backend lint
        - yarn --cwd backend test --coverage
        - yarn --cwd backend audit
        - yarn --cwd web lint
        - yarn --cwd web cypress:ci:start
    - stage: Release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: release
branches:
  only:
    - dev
    - release
