version: '3'
services:
  database:
    image: postgres
    volumes:
      - postgresql:/var/lib/postgresql/database
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
  server:
    build: .
    volumes:
      - .:/app
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - IAM_ID=${IAM_ID}
      - IAM_SECRET=${IAM_SECRET}
      - S3_URL=${S3_URL}
    command: bash -c 'yarn install --prod false && yarn db:migrate-dev && yarn start'
    ports:
      - 5000:5000
    depends_on:
      - database
volumes:
  postgresql:
