name: Tests
on:
  push:
    branches:
      - dev
      - release
  pull_request:
    branches:
      - dev
      - release
jobs:
  main:
    runs-on: ubuntu-16.04
    services:
      database:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: balans
          POSTGRES_PASSWORD: balans
          POSTGRES_DB: balans_test
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [12.x]
    env:
      PORT: 4000
      SECRET: gh-actions
      DB_HOSTNAME: localhost
      DB_USERNAME: balans
      DB_PASSWORD: balans
      DB_NAME: balans
      REACT_APP_API_URL: http://localhost:4000/graphql
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn --cwd backend install
          yarn --cwd web install
      - name: Migrate DB
        run: |
          yarn --cwd backend db:test:migrate
      - name: Run backend tests
        run: yarn --cwd backend test
      - name: Run backend
        run: |
          NODE_ENV=cypress yarn --cwd backend dev &
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./web
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          start: yarn start
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        if: github.ref == 'refs/heads/release'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
