name: Tests
on:
  push:
    branches:
      - dev
      - release
  pull_request:
    branches:
      - dev
      - release
jobs:
  main:
    runs-on: ubuntu-16.04
    services:
      database:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: balans
          POSTGRES_PASSWORD: balans
          POSTGRES_DB: balans_test
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [12.x]
    env:
      PORT: 4000
      SECRET: gh-actions
      DB_HOSTNAME: localhost
      DB_USERNAME: balans
      DB_PASSWORD: balans
      DB_NAME: balans
      REACT_APP_API_URL: http://localhost:4000/graphql
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn --cwd backend install
          yarn --cwd web install
      - name: Migrate DB
        run: |
          yarn --cwd backend db:test:migrate
      - name: Run backend tests
        run: yarn --cwd backend test
      - name: Run backend
        run: |
          NODE_ENV=cypress yarn --cwd backend dev &
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./web
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          wait-on-timeout: 120
          start: yarn start
      - name: Build staging client
        if: github.ref == 'refs/heads/dev'
        env:
          REACT_APP_API_URL: https://balans-staging.herokuapp.com/graphql
          NODE_ENV: production
        run: yarn --cwd web build
      - name: Deploy staging client
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/dev'
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: staging.balans.cf
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
          SOURCE_DIR: 'web/build'
      - name: Deploy staging backend
        uses: akhileshns/heroku-deploy@v3.6.8
        if: github.ref == 'refs/heads/dev'
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'balans-staging'
          heroku_email: 'iaacosta@uc.cl'
          usedocker: true
          appdir: 'backend'
      - name: Build production client
        if: github.ref == 'refs/heads/release'
        env:
          REACT_APP_API_URL: https://balans-production.herokuapp.com/graphql
          NODE_ENV: production
        run: yarn --cwd web build
      - name: Deploy production client
        uses: jakejarvis/s3-sync-action@master
        if: github.ref == 'refs/heads/release'
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: balans.cf
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
          SOURCE_DIR: 'web/build'
      - name: Deploy production backend
        uses: akhileshns/heroku-deploy@v3.6.8
        if: github.ref == 'refs/heads/release'
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'balans-production'
          heroku_email: 'iaacosta@uc.cl'
          usedocker: true
          appdir: 'backend'
      - name: Semantic release
        if: github.ref == 'refs/heads/release'
        run: npx semantic-release
